# Generated by Django 5.2 on 2025-05-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
