# Generated by Django 5.2 on 2025-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
    ]
