# Generated by Django 5.2 on 2025-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_posted_taskanswer_taskpost_taskanswer_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpost',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
